#!/usr/bin/env zsh

# Checks if there's a frame open
emacsclient -n -e "(if (> (length (frame-list)) 1) 't)" 2> /dev/null | grep t &> /dev/null

if [ "$?" -eq "1" ]; then
  echo "Emacs already running, connecting..."
  emacsclient -a '' -nqc "$@" &> /dev/null
else
  echo "Starting Emacs with a server..."
  emacsclient -nq "$@" &> /dev/null
fi
